### PR TITLE
Fix spelling of choose from chose.

### PR DESCRIPTION
**Pull request by romeojulietthotel**
Don't know how to update the .po/.mo translation files. I can do that too if you tell me how.

### CODE REVIEW

**Comment by nitely** [comment]
Translations strings are IDs. So you can't change them without changing every .po file. The way to handling a translation mistake is to change the translation for that string within the .po file (the english one in this case). Since I'm using [transifex](http://community.spirit-project.com/topic/21/translations/) it must be change there.

**Comment by nitely** [comment]
Hey

Can you revert the ID change? then translate that msg within the [.po file](https://github.com/nitely/Spirit/blob/master/spirit/topic/locale/en/LC_MESSAGES/django.po) (just fill the `msgstr`). Once you do that I'll update the transifex source and check whether it works or not.

To generate .mo files just run`$ manage.py spiritmakelocales`. But don't worry about that. I do it before a new release and I won't merge changes containing binary data for obvious reasons.

**Comment by romeojulietthotel** [comment]
I don't know much at all about translation (know nothing about transifex) but I understand now that the .mo are the binary result of the .po and understand why you wouldn't want to take the .mo files. I wouldn't either...oh wait...I guess I have to take them. Hmmm.

**Comment by nitely** [comment]
Yeah, but don't worry about .mo files. The require change is just filling
the msgstr for that msgid within the .po file.

I guess I can do it. I'm not sure it will work, though. Another way would
be to update the msgid for every .po file as you suggested. A
search&replace would do.

**Comment by nitely** [comment]
Fixed in https://github.com/nitely/Spirit/commit/8abb20468299cc4dbd8a1e4d9634b20c7a64f2e0 , I'll have to check how transifex handles that

**Pull request closed without merging**
