### PR TITLE
Support for Django 1.9

### LINKED ISSUE #91: Add Support for Django 1.9
from django.utils.datastructures import SortedDict
ImportError: cannot import name 'SortedDict'

### PR DESCRIPTION
**Pull request by RobertKolner**
This pull request fixes  #91 by doing following things:
- Upgrade django-haystack and django-djconfig to versions supporting Django 1.9
- Fix the issue with using the deprecated `django.db.models.loading.get_model`
- Fix the tests broken by the upgrade
- Remove support for Python 3.3

All tests seem to pass now, but I have to admit that I haven't tried using this version in a project yet.

### CODE REVIEW

**Comment by nitely** [comment]
Looks good!

> All tests seem to pass now, but I have to admit that I haven't tried using this version in a project yet.

Well, tests are pretty extensive. If they pass and you can actually enter the forum on local, then everything it's probably ok.

**Comment by RobertKolner** [comment]
Oh, right, I meant that I didn't use it anywhere besides the provided code. Both tests and the example-project seem to work flawlessly.

**Comment by nikolaik** [comment]
Nice, looking forward for a new release with this!

**Comment by nitely** [comment]
@RobertKolner Merging this now, thanks man!

**Pull request merged**
