### PR TITLE
Update topic.py

### PR DESCRIPTION
**Pull request by oduvan**

### CODE REVIEW

**Comment by nitely** [comment]
Is there a way to automatically fix the string for every (locale) translation?

To fix this, I'd just translate that string in the [english locale](https://github.com/nitely/Spirit/blob/master/spirit/locale/en/LC_MESSAGES/django.po#L71). Since we have a [transifex project](https://www.transifex.com/projects/p/spirit/), it should be fix there.

**Comment by nitely** [comment]
[Here](http://stackoverflow.com/questions/8288050/can-i-automatically-update-msgids-in-gettexts-po-files-for-trivial-text-change) there is a related stackoverflow question, it's seems there is no way to fix this (other than search&replace) for every locale file.

The translation files are out of date at the moment, I'll update them (sync them to transifex) in the experimental branch and let you know when that's done, in case you want to submit another pull request.

**Comment by oduvan** [comment]
Where can I read about this experemental branch?

What is inside?

Where it is going to be released?

What issues are holding it from releasing?

**Comment by nitely** [comment]
[Here](https://github.com/nitely/Spirit/branches) there are all the current branches. I made many changes to the project structure, mostly. I think the only real thing keeping me from releasing it is that it has not been deployed to community.spirit-project.com. I will try to get to it this weekend.

**Comment by oduvan** [comment]
Right now we are using it here https://forum.empireofcode.com while closed beta testing

**Comment by oduvan** [comment]
Hi :)

When do you think we can update it?

**Comment by nitely** [comment]
Hi!

I've decided to make all the *breaking changes* I want before releasing it, ie: there wont be a way to directly upgrade from 0.1 to 0.4 but the upgrade path will be from 0.1 to 0.3 and then to 0.4 instead.
I don't want to force people to do something like that in future releases, other than the next one (no way to avoid it AFAIK). This is coz I'm changing the structure to an app composed by apps (ie: spirit.apps.comments, spirit.apps.topic, etc) instead of a big one app.

So, I'm making sure everything will go smoothly after the next release, that's why it's taking so long.

**Comment by auvipy** [comment]
that would be a better to move on moduler approach

**Comment by auvipy** [comment]
version 3.0 released? when it will be?

**Pull request closed without merging**
