### PR TITLE
Feature/remove jquery

### PR DESCRIPTION
**Pull request by nitely**
WIP

### CODE REVIEW

**Comment by ababic** [comment]
Hi @nitely. I appreciate that you don't want to be held to strict timelines, but do you a (rough) idea when this work might be completed? 

We have been asked to upgrade jQuery to version 3 on a forum we created for a client, but obviously this isn't possible currently due to compatibility issues with a few of the dependencies.

**Comment by nitely** [comment]
@ababic this is almost complete IIRC. Can you give until this weekend and ping me again?

**Comment by ababic** [comment]
@nitely Thank you for the prompt reply. Sure, I'll keep an eye on things and ping again in a week or so.

**Comment by nitely** [comment]
@ababic remember to follow the upgrade steps [0] (mainly backing up the db and running `spiritupgrade` command). It'd be great If you can try it before the next release and let me know about any regressions. Tests do pass and I tried it myself, everything seems to work well.

[0] https://spirit.readthedocs.io/en/latest/upgrade.html

**Comment by ababic** [comment]
Thanks @nitely. Much appreciated! We're running from a custom fork, with quite a heavily customised front-end, so things may take a while to untangle. However, the client seems keen to prioritise it (in the next few weeks), so I will let you know how it goes.

**Pull request merged**
