### PR TITLE
Feature/anti double post

### PR DESCRIPTION
**Pull request by nitely**
* Prevent user from posting the same comment, topic or private topic twice in a round
* There is a threshold time (`settings.ST_DOUBLE_POST_THRESHOLD_MINUTES`) the user has to past before double posting. This is so comments like *"bump"* or whatever, after some time are allowed.
* It's possible to send the same comment to multiple topics and to send the same topic to multiple categories.
* It's also possible to send the same message as the previous comment, assuming they are not from the same user.
* The implementation builds a hash from the comment, currently it's server side. But there is a *[comment|topic]_hash* field that when populated/sent it'll avoid doing the hash calculation, so it can be done with JS and then appended to the form before POSTing. Since it gets saved into the user's model and it's only used for comparasions it does not matter someone sends something other than a hash.
* The operation is atomic, meaning there is no way to bypass it by sending multiple post at exactly the same time.

### CODE REVIEW

**Comment by nitely** [comment]
@alesdotio can you review this?

**Comment by alesdotio** [comment]
Awesome! Looks good.

I merged it with my fork, but it seems I can't post more than once every 30min now (no matter the content). Maybe I messed something up, although all tests pass...

**Comment by alesdotio** [comment]
I narrowed down the problem to this line https://github.com/nitely/Spirit/blob/master/spirit/core/utils/ratelimit/ratelimit.py#L76

I'm not really sure what this does? Isn't the cache set with cache.add in the line above?

**Comment by nitely** [comment]
> I narrowed down the problem to this line https://github.com/nitely/Spirit/blob/master/spirit/core/utils/ratelimit/ratelimit.py#L76
> 
> I'm not really sure what this does? Isn't the cache set with cache.add in the line above?

`add` will add the key if it has expired or does not exists. If it has not expired, it does nothing.

I just debugged this. It's a bug in Django. `LocMemCache` overrides the `incr()` method and increases the cache-key value and nothing else is done. `DatabaseCache` uses the base method (`django.core.cache.backends.base.BaseCache`) which calls `set()` without passing a timeout, so the default timeout is used (5 minutes).

Also, since `set()` *resets* the timeout, if you try to publish a comment before the 5 minutes has past you won't ever be able to post, that's prolly why you had to wait more than 5 minutes.

There is no test for this coz the only possible test I can think of would be testing Django (not Spirit).

**Comment by alesdotio** [comment]
How about overriding the CACHES setting for that specific test?

**Comment by nitely** [comment]
> How about overriding the CACHES setting for that specific test?

The there is nothing testing the cache timeout is being reseted. Django should be testing that not Spirit. Do you want to report this in their tracker? I can do it otherwise.

**Comment by alesdotio** [comment]
Go ahead. But is there any way we can fix this in Spirit?

**Comment by nitely** [comment]
[I opened the ticket](https://code.djangoproject.com/ticket/26619).

> But is there any way we can fix this in Spirit?

Not sure. Reversing [6985c1014e8972ea7f1020746d80a81b20da2fb8](https://github.com/nitely/Spirit/commit/6985c1014e8972ea7f1020746d80a81b20da2fb8) is one way.

**Comment by alesdotio** [comment]
This change actually fixes double posts for users with bad connections (which happens surprisingly often) so it would be really nice to have.

**Comment by nitely** [comment]
The cache issue is not related to this PR. The "offending" commit is *already* in master :sweat_smile:

**Comment by nitely** [comment]
> ... is there any way we can fix this in Spirit?

Should be fixed now.

**Comment by nitely** [comment]
@alesdotio Can you try this again? should I just merged it?

**Comment by nitely** [comment]
I just rebased this, so it has latest changes to master.

**Comment by alesdotio** [comment]
Please don't use rebase again if possible, I have to merge my changes all over again 😭

**Comment by nitely** [comment]
Sorry, I didn't think you were merging to your fork  :cold_sweat: . I'll merge instead of rebase next time.

**Comment by alesdotio** [comment]
Doesn't seem to work at all. After the rate limit I can double post again.

**Comment by alesdotio** [comment]
Oops, sorry I had the wrong version installed in my virtualenv 😓 . 

Seem to work now! Awesome 😄

**Comment by alesdotio** [comment]
I think the example app needs ``ST_RATELIMIT_SKIP_TIMEOUT_CHECK = False`` otherwise I think it's good to go!

**Comment by nitely** [comment]
`ST_RATELIMIT_SKIP_TIMEOUT_CHECK = False` is the default. Since all example settings import all `spirit.settings`, then it should be setted that way.

That check is there for those who want to use default as the rate-limiter cache or a cache backend that does not have a timeout option.

I'm merging this then.

**Pull request merged**
