### PR TITLE
improved German translation

### PR DESCRIPTION
**Pull request by rbergmair**
I'm a German native speaker, and I took a stab at improving the German translation tokens.

* added translations for some tokens that previously didn't have any translations at all
* fixed some translations that I found highly unidiomatic.  (For example "Vorlieben" for "Preferences" sounds pretty weird to my ear).
* fixed some inconsistencies in spelling conventions e.g. upper-casing of personal pronouns (e.g. "Du" and "Dich" was previously upper-cased in line with conventions for writing letters in some, but not all cases.  I uniformly used the lower-case version instead).

### CODE REVIEW

**Comment by rbergmair** [comment]
I've created a join request.

**Comment by nitely** [comment]
I just accepted it.

**Comment by nitely** [comment]
mmh, if you remove all the binaries, at some point I'll merge it.

**Comment by rbergmair** [comment]
That would be much appreciated, and thanks a lot for the great work you've done with this piece of software in general!

Closing in favour of #328.

**Pull request closed without merging**
