### PR TITLE
Support alternate file storage backends for comment images

### LINKED ISSUE #158: Support for alternate file storages
I was looking into using S3 for static and media storag, but then realized Spirit does not support it. I would suggest using [django-storages](https://github.com/jschneier/django-storages).

### PR DESCRIPTION
**Pull request by alesdotio**
Fixes #158

Tested and works great with django-storages and S3!

One small catch is that the default django FileSystemStorage does not overwrite files but renames them. So now if the same user uploads the same image twice it will actually be two different files. Not a big deal in my opinion, but you could fix that by using a slightly modified storage class, like this https://gist.github.com/fabiomontefuscolo/1584462.

### CODE REVIEW

**Comment by nitely** [comment]
Looks good!

> One small catch is that the default django FileSystemStorage does not overwrite files but renames them. So now if the same user uploads the same image twice it will actually be two different files. Not a big deal in my opinion

Yeah, I was thinking in removing that feature. What about using [shortuuid](https://github.com/skorokithakis/shortuuid) (based in `uuid4`)?

**Comment by alesdotio** [comment]
> What about using shortuuid (based in uuid4)?

It looks better, yes, but I wouldn't change it just for the sake of it. Might also be problematic with case-insensitive backends.

**Comment by nitely** [comment]
> It looks better, yes, but I wouldn't change it just for the sake of it.

I see no point in generating a hash out of a file if it won't prevent duplicated files. I don't think it's the best solution for that either since images are stored by user (`user_id/image.jpg`).

> Might also be problematic with case-insensitive backends.

Good point. The alphabet can be set to numbers and lowercase letters. The uuid gets a bit larger, though.

**Comment by alesdotio** [comment]
> I see no point in generating a hash out of a file if it won't prevent duplicated files.

That depends on the storage backend. The S3 backend, for example, overwrites files.

**Comment by nitely** [comment]
Ok. I'll add a setting when/if I make that change.

Merging this :tada:

**Pull request merged**
