### PR TITLE
Not all site users should be listed by spirit

### PR DESCRIPTION
**Pull request by sureshvv**
Many members of a site may want to remain unlisted in spirit.

### CODE REVIEW

**Comment by nitely** [comment]
There should be a way to list them, or no way to unset this boolean in Spirit. Otherwise there's no way to reverse the operation if you don't know the user edit URL.

Also, what's the point of this? it does not seem useful on its own.

Also, tests are missing.

**Comment by sureshvv** [comment]
The UserProfileForm has a checkbox that can be unset to unlist the users. This is done by Spirit admin.

I can write the tests if you are ok with the idea in general.

**Comment by nitely** [comment]
I don't get it, why would I want to hide a user from the user list?

**Comment by sureshvv** [comment]
When a single django instance is running multiple independent apps and users from one should not be mixed with the users of another.

**Comment by nitely** [comment]
those users can still access Spirit, so they are spirit users...
In any case this is something that should be done in another app, not in Spirit...

**Comment by sureshvv** [comment]
Hmmm... Can you tell me how I can make the other app prevent Spirit from listing the users?

You are right in that they would be able to access Spirit unless middleware prevents that.

**Comment by nitely** [comment]
You can override the template and add a filter there I believe.

**Comment by sureshvv** [comment]
Good. I will try that.

**Pull request closed without merging**
