### PR TITLE
Added support for comment search

### LINKED ISSUE #57: Search won't search in comments
I did 

```Bash

$ python manage.py rebuild_index --noinput
Removing all documents from your index because you said so.
All documents removed.
Indexing 3 topics
$ python manage.py runserver 0:8001
Performing system checks...

System check identified no issues (0 silenced).
July 06, 2015 - 18:18:18
Django version 1.7.8, using settings 'forum.settings'
Starting development server at http://0:8001/
Quit the server with CONTROL-C.
/local/lib/python2.7/site-packages/django/template/base.py:290: RemovedInDjango18Warning: 'The `firstof` template tag is changing to escape its arguments; the non-autoescaping version is deprecated. Load it from the `future` tag library to start using the new behavior.
  compiled_result = compile_func(self, token)

[06/Jul/2015 18:18:32] "GET /search/?q=Wowo HTTP/1.1" 200 5796

```

Results

There are no search results.

### PR DESCRIPTION
**Pull request by clintonb**
Comments are indexed as part of topics.

Fixes #57
Replaces #69

@nitely please review

### CODE REVIEW

**Comment by clintonb** [comment]
@nitely please let me know if you have any feedback.

**Comment by nitely** [comment]
I'm set on implementing this myself, see branch `search_within_comments`. Apparently this feature prove not to be so simple. This PR does an `all()` potentially loading a bazillion comments in memory, it does not stripes HTML tags from text, it retrieves the whole table instead of just the comment (ie: using `values()`) and there is more I can't remember right now (hopefully it will come while coding).

**Comment by clintonb** [comment]
@nitely good points. One alternative, and something I considered, would be to store comments in their own index. This resolves the memory issues and gives you the flexibility to search by comments or topics.

**Comment by nitely** [comment]
I would prefer show something like:

* Matched topic
    * Matched Comment
    * Matched Comment
* Matched topic
    * Matched Comment

But AFAIK this is not possible, (except by running multiple search queries and having all comments indexed twice :worried: :astonished: )

**Pull request closed without merging**
